name: app
description: Architecture Demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.2
  get_it: ^6.1.1
  dartz: ^0.10.0-nullsafety.2
  flutter_bloc: ^7.0.0
  dio: ^4.0.0

dev_dependencies:
  build_runner: ^1.11.1
  flutter_test:
   sdk: flutter
  lint: ^1.5.3
  freezed: ^0.14.0
  mockito: ^5.0.7
  bloc_test: ^8.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
