// Mocks generated by Mockito 5.0.7 from annotations
// in app/test/features/home/data/remote/cat_remote_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:app/integrations/helpers/http_helper.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeHttpResponse extends _i1.Fake implements _i2.HttpResponse {}

/// A class which mocks [HttpHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpHelper extends _i1.Mock implements _i2.HttpHelper {
  MockHttpHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.HttpResponse> post(String? path, {dynamic data}) =>
      (super.noSuchMethod(Invocation.method(#post, [path], {#data: data}),
              returnValue: Future<_i2.HttpResponse>.value(_FakeHttpResponse()))
          as _i3.Future<_i2.HttpResponse>);
  @override
  _i3.Future<_i2.HttpResponse> delete(String? path) =>
      (super.noSuchMethod(Invocation.method(#delete, [path]),
              returnValue: Future<_i2.HttpResponse>.value(_FakeHttpResponse()))
          as _i3.Future<_i2.HttpResponse>);
  @override
  _i3.Future<_i2.HttpResponse> get(String? url, {Duration? cacheTime}) => (super
          .noSuchMethod(Invocation.method(#get, [url], {#cacheTime: cacheTime}),
              returnValue: Future<_i2.HttpResponse>.value(_FakeHttpResponse()))
      as _i3.Future<_i2.HttpResponse>);
}
